title: "LLNL Theme for Jekyll"
author: "Ian Lee <lee1001@llnl.gov>"
description: "LLNL Jekyll Template"

# Correct linking GitHub Project pages
# Note leading slash in baseurl
githubrepo: Jekyll-LLNL-Theme
baseurl: /Jekyll-LLNL-Theme

permalink: pretty

kramdown:
  auto_ids: true
